### ISSUE TITLE
supporting Julia v0.6 and lower?

### ISSUE THREAD

**Issue by mweastwood** [JuliaAstro/FITSIO.jl#100]
Now that Julia v0.7-alpha is out the door, we should be looking to update FITSIO.jl for the latest version. However, Julia v1.0 is supposed to be unchanged from v0.7 (just dropping deprecation warnings). Therefore, this seems to be a sensible place to drop support for earlier versions and focus on 1.0+, which should hopefully be a stable platform for a number of years.

As an added bonus, [FemtoCleaner](https://discourse.julialang.org/t/femtocleaner-usage-howto/11762) will do a lot of the work for us if we're willing to drop support for v0.6 and lower.

Personally, I think we should tag one more version that includes the latest changes on v0.6 and then push forward on v0.7 only.

Thoughts?

**Comment by kbarbary** [comment]
I agree.

**Comment by giordano** [comment]
Julia versions 0.6 and 0.7 had been [deprecated one month ago](https://discourse.julialang.org/t/julia-0-6-and-0-7-are-now-officially-unmaintained/20449) (this is means that at some point soon new version of packages supporting julia <= v0.7 will not be accepted, also to stop using METADATA.jl), I think there is no more reason maintaining support for them any longer.  I went ahead and opened #110

**Comment by giordano** [comment]
Closed by #110
