### ISSUE TITLE
Dependency compatibility bounds are too loose

### ISSUE THREAD

**Issue by jishnub** [JuliaAstro/FITSIO.jl#130]
At present the compat entries are https://github.com/JuliaAstro/FITSIO.jl/blob/a9a14fba3919d8f0ad8d0f64c9a59679d51ff98e/Project.toml#L11-L12

Perhaps we should shift to the caret bounds from the inequalities? In any case the julia registry places an upper bound on the julia version, but apparently it doesn't on the other dependencies.

https://github.com/JuliaRegistries/General/blob/d001c9bc98ddb251e2c025257d3c8d94ab032fa7/F/FITSIO/Compat.toml#L7-L8

**Comment by giordano** [comment]
You are correct and pull requests are always welcome :wink:

**Comment by jishnub** [comment]
Thanks, I'll submit a PR soon that addresses this and #129.

**Comment by jishnub** [comment]
Fixed by #131
