### ISSUE TITLE
getindex(FITS, String) does not work

### ISSUE THREAD

**Issue by aplavin** [JuliaAstro/FITSIO.jl#141]
In version 0.16 this `getindex` method stopped working (works in 0.15):
https://github.com/JuliaAstro/FITSIO.jl/blob/ac1e773ed7adaa7f838883ca9580173561a4ad3d/src/fits.jl#L111
It gives the following stacktrace:
```julia
  UndefVarError: fits_movnam_hdu not defined
  Stacktrace:
   [1] getindex(::FITSIO.FITS, ::String, ::Int64) at /home/runner/.julia/packages/FITSIO/KYCVW/src/fits.jl:113
   [2] getindex at /home/runner/.julia/packages/FITSIO/KYCVW/src/fits.jl:112 [inlined]
```
The `fits_movnam_hdu` function is indeed used here:
https://github.com/JuliaAstro/FITSIO.jl/blob/ac1e773ed7adaa7f838883ca9580173561a4ad3d/src/fits.jl#L113
But I cannot find it defined anywhere in the FITSIO.jl repo. Was it just removed at some point? Everything is fine with version 0.15.

**Comment by giordano** [comment]
> Was it just removed at some point?

It was moved to `CFITSIO.jl` here: https://github.com/JuliaAstro/CFITSIO.jl/blob/9a1acf6c9ee278849a929d549c884076820a03d0/src/CFITSIO.jl#L812-L830

**Comment by aplavin** [comment]
Then I guess the reason why `FITSIO.jl` `getindex` method got broken is because `fits_movnam_hdu` is not imported here:
https://github.com/JuliaAstro/FITSIO.jl/blob/master/src/FITSIO.jl#L38-L73
Right?

**Comment by giordano** [comment]
Probably

**Comment by aplavin** [comment]
I created a PR https://github.com/JuliaAstro/FITSIO.jl/pull/142 which imports the three functions required by this getindex method.

**Comment by giordano** [comment]
I guess we can close this issue now?
