### ISSUE TITLE
ERROR: FITSFile not defined

### ISSUE THREAD

**Issue by fabienbaron** [JuliaAstro/FITSIO.jl#32]
With the FITSIO package installed and Pkg.update() done, I get the following error on Kubuntu 15.04. Not sure what's going on...

Julia Version 0.3.2, x86_64-linux-gnu
julia> using OIFITS
Warning: could not import FITSIO.fits_get_errstatus into OIFITS
ERROR: FITSFile not defined
in eval at ./no file
 in include212 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
 in include_from_node11801 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
 in include212 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
 in include_from_node11801 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
 in include212 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
 in include_from_node11801 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading /home/baron/.julia/v0.3/OIFITS/src/fix-fitsio.jl, in expression starting on line 127
while loading /home/baron/.julia/v0.3/OIFITS/src/oifile.jl, in expression starting on line 17
while loading /home/baron/.julia/v0.3/OIFITS/src/OIFITS.jl, in expression starting on line 51

**Comment by kbarbary** [comment]
The latest version of FITSIO.jl has a breaking API change (see [NEWS.md](https://github.com/JuliaAstro/FITSIO.jl/blob/master/NEWS.md) and the latest [docs](https://julia-fitsio.readthedocs.org/en/latest/cfitsio.html)) and OIFITS hasn't caught up yet. Sorry!

cc: @emmt Any plans for an updated OIFITS asap?

**Comment by kbarbary** [comment]
Closing for now, as this is downstream of FITSIO.

**Comment by emmt** [comment]
I have made the modifications to have OIFITS.jl working with FITSIO.jl v0.6
Fabien can you check whether it is functionnal for you before I bump the version number? Thanks!

**Comment by fabienbaron** [comment]
Works perfectly (Julia 0.3.8) ! Thanks Eric !
