### ISSUE TITLE
FITSIO doesn't seem to check if CFITSIO is already installed.

### ISSUE THREAD

**Issue by rcthomas** [JuliaAstro/FITSIO.jl#49]
It always seems to try to download and build CFITSIO.

**Comment by StefanKarpinski** [comment]
You probably want to provide the output of `versioninfo()` as well.

**Comment by rcthomas** [comment]
Thanks, sorry!

    julia> versioninfo()
    Julia Version 0.5.0-dev+2918
    Commit 1eacbbb* (2016-02-28 16:56 UTC)
    Platform Info:
      System: Linux (x86_64-suse-linux)
      CPU: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas64_
      LIBM: libopenlibm
      LLVM: libLLVM-3.7.1

**Comment by StefanKarpinski** [comment]
Thanks. How did you install CFITSIO? System package manager or manually from source?

**Comment by kbarbary** [comment]
Hmm... I thought that BinDeps (which is how FITSIO satisfies dependencies) checks for an existing library before  trying to satisfy the dependency in another way, but I might be wrong about that.

**Comment by StefanKarpinski** [comment]
That's why I was asking about how CFITSIO was installed. If it's installed via system package manager, then that version should get picked up by BinDeps if it's working right. If it was installed manually from source, it's pretty hard to make the package reliably use that version.

**Comment by rcthomas** [comment]
It's built from source.   Does BinDeps look at pkg-config?

**Comment by mweastwood** [comment]
Closed by #97. FITSIO.jl now uses BinDeps2 to download pre-compiled binaries.
