### ISSUE TITLE
License clash? (MIT/GPL)

### ISSUE THREAD

**Issue by ziotom78** [JuliaAstro/FITSIO.jl#5]
I see that FITSIO.jl has been released under the MIT license. However, the purpose of the code is to provide a link to the CFITSIO library, which is covered by the GPL (see http://heasarc.nasa.gov/docs/software/fitsio/c/f_user/node9.html).

Given the viral nature of the GPL, wouldn't this require that FITSIO.jl be released under the GPL too? The CFITSIO license states that "…any software that uses the CFITSIO library (which in turn uses the gzip code) must conform to the provisions in the GNU General Public License".

I know that different opinions exist on this topic (see http://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works), but I wanted to know the author's position regarding this delicate issue.

(By the way: I am not a fan of the GPL, as I hate its viral nature. As a matter of fact, http://heasarc.nasa.gov/docs/software/fitsio/c/f_user/node9.html states that CFITSIO has been released under the GPL because it links to some GPL'ed code from zlib and AIPS. But I think it is important to fix this kind of issues.)

**Comment by kbarbary** [comment]
For the record and for anyone finding this issue via searches, I recently discovered that the entirety of CFITSIO has in fact been liberally licensed since v3.26, released 2010 December 30. From the [release notes](http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt), under that version:

```
   - replaced all the source code in CFITSIO that was distributed under the
     GNU General Public License with freely available code.  In particular,
     the  gzip file compression and uncompression code was replaced by the
     zlib compression library.  Thus, beginning with this version 3.26 of CFITSIO,
     other software applications may freely use CFITSIO without necessarily
     incurring any GNU licensing requirement.  See the License.txt file for
     the CFITSIO licensing requirements.
```

So now there's really no problem: FITSIO.jl is entirely MIT-licensed, even in combination with CFITSIO.
