### ISSUE TITLE
Docs: dictionaries need to be created with Dict()

### ISSUE THREAD

**Issue by hsgg** [JuliaAstro/FITSIO.jl#88]
Hi, we were following the documentation at [https://julia-fitsio.readthedocs.io/en/latest/](). The last code block is supposed to generate a `Dict()`. However, we get

    julia> data = ["col1"=>[1., 2., 3.], "col2"=>[1, 2, 3]];
    
    julia> write(f, data)
    ERROR: MethodError: no method matching bitpix_from_type(::Type{Pair{String,Array{Float64,1}}})
    Closest candidates are:
      bitpix_from_type(::Type{UInt8}) at /home/hsgg/.julia/v0.6/FITSIO/src/libcfitsio.jl:140
      bitpix_from_type(::Type{Int16}) at /home/hsgg/.julia/v0.6/FITSIO/src/libcfitsio.jl:140
      bitpix_from_type(::Type{Int32}) at /home/hsgg/.julia/v0.6/FITSIO/src/libcfitsio.jl:140
      ...
    Stacktrace:
     [1] fits_create_img(::FITSIO.Libcfitsio.FITSFile, ::Type{Pair{String,Array{Float64,1}}}, ::Array{Int64,1}) at /home/hsgg/.julia/v0.6/FITSIO/src/libcfitsio.jl:735
     [2] #write#3(::Void, ::Void, ::Void, ::Function, ::FITSIO.FITS, ::Array{Pair{String,Array{Float64,1}},1}) at /home/hsgg/.julia/v0.6/FITSIO/src/image.jl:168
     [3] write(::FITSIO.FITS, ::Array{Pair{String,Array{Float64,1}},1}) at /home/hsgg/.julia/v0.6/FITSIO/src/image.jl:166
     [4] macro expansion at ./REPL.jl:97 [inlined]
     [5] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

We are using julia-0.6.0.

**Comment by mweastwood** [comment]
Looks like the docs need to be updated. The syntax for creating `Dict`s in Julia has changed since that example was written.

Try this instead

```julia
julia> using FITSIO

julia> f = FITS("newfile.fits", "w");

julia> data = Dict("col1"=>[1., 2., 3.], "col2"=>[1, 2, 3])
Dict{String,Any} with 2 entries:
  "col2" => [1, 2, 3]
  "col1" => [1.0, 2.0, 3.0]

julia> write(f, data)

julia> read(f[2], "col1")
3-element Array{Float64,1}:
 1.0
 2.0
 3.0
```

**Comment by mweastwood** [comment]
Oh, just kidding. The latest docs are already up to date. They are now hosted here: http://juliaastro.github.io/FITSIO.jl/stable/

We should probably remove or redirect the readthedocs site.

**Comment by nolta** [comment]
Deleted.

**Comment by kbarbary** [comment]
:+1: I'm removing the sphinx docs source in #89.

**Comment by hsgg** [comment]
Thanks! I had missed the markdown docs.
