### ISSUE TITLE
fits_get_colnum should be case-sensitive

### ISSUE THREAD

**Issue by hbouy** [JuliaAstro/FITSIO.jl#98]
It seems that fits_get_colnum is set-up to be always case insensitive.
I know a fair number of astronomical catalogs that use case-sensitive column names.
The Gaia DR2 catalog (as offered on [CDS ViZieR](http://vizier.u-strasbg.fr/viz-bin/VizieR-3?-source=I/345/gaia2)) released yesterday is one of them (e.g. the b_Teff and B_Teff columns).
It would be great to make it case sensitive by default.
thanks

**Comment by mweastwood** [comment]
Does changing `0` to `1` on this line here get you the behavior you're looking for?

https://github.com/JuliaAstro/FITSIO.jl/blob/2ded0179af50a731c97a9bae384535659ff53838/src/libcfitsio.jl#L940

Case sensitivity seems like a sensible default, but at the very least this should be configurable.

**Comment by giordano** [comment]
> Case sensitivity seems like a sensible default, but at the very least this should be configurable.

What about a keyword argument of `Bool` type?

**Comment by kbarbary** [comment]
Agreed. It should be easy to add a `Bool` parameter or keyword arg to `fits_get_colnum`. I don't know why the default `0` (case insensitive) was chosen. I agree that case-sensitive would be a better default. Changing the default is technically breaking, but I'm not sure there are so many users that it is worth figuring out how to issue a good deprecation warning. What do you all think?

In the high level interface, we should add a keyword argument `case_sensitive=true` to `read(::TableHDU, ::String)`. Alternatively we could have a global (module-wide) configuration setting. This might make sense as users will probably wish to read many columns with the same setting.

**Comment by giordano** [comment]
A global setting can be made thread-safe, I've already done something similar recently.  I'm not sure if I 100% agree with it, but I see your point about portability.  In #99 I'm fixing the reported issue with a simple optional keyword only.

**Comment by kbarbary** [comment]
Good points @mweastwood.

**Comment by kbarbary** [comment]
While we are allowed to make breaking changes like this, I'm wondering if
this change might be disruptive enough to warrant a deprecation warning.
There might be enough FITSIO users at this point to make it worthwhile.

However, the deprecation warning would have to be done carefully to not be
annoying. E.g., only warn when case-insensitive returns a match but
case-sensitive does not. I think it's fine to only do this in the high-end
level interface.

**Comment by giordano** [comment]
Anyway I'm working on a fix in Celeste to use the names with proper capitalization.

Regarding the depwarn, would that require a `try`-`catch`?
